### PR TITLE
Improve testing setup and start documenting contribution guidelines

### PR DESCRIPTION
**Pull request by zeke**
Salut, @millette! 👋 

I was planning to write a Libraries.io client tonight, but came across this project and was intrigued by the bells and whistles: ava, async/await, nyc, etc...

This PR aims to make it easier for developers to develop and contribute to the project.

### CODE REVIEW

**Comment by millette** [comment]
I must have generated the module with https://github.com/millette/generator-nm-standard which itself was based on https://github.com/sindresorhus/generator-nm - so that explains most dev dependencies.

I will get your contribs merge asap. Thanks :-)

**Comment by zeke** [comment]
That was fast!

**Comment by millette** [comment]
I made another release when I realized I had to move dotenv from dev-deps to deps. Now everything is updated, all the way to http://meridas.rollodeqc.com/millette/

**Comment by zeke** [comment]
🎉

**Pull request merged**
